Add missing die() definition
In the haste of pre-release refactoring, some things got missed.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,6 +1,11 @@
 #!/bin/bash
 set -e
 
+die() {
+    echo >&2 "ERROR: $*"
+    exit 1
+}
+
 B=""
 while [ $# -gt 1 ]; do
     case "$1" in
diff --git a/sstate-publish b/sstate-publish
--- a/sstate-publish
+++ b/sstate-publish
@@ -1,6 +1,11 @@
 #!/bin/sh
 set -e
 
+die() {
+    echo >&2 "ERROR: $*"
+    exit 1
+}
+
 B=""
 GEN=""
 DST=""
